# File names are either absolute or relative to the parent folder of the
# vhdl_ls.toml file and supports glob-style patterns.

[libraries]

lib1.files = [
  'CalculatorVHDL.vhd',
  'FSM.vhd',
  'Fulladder.vhd',
  'BinaryAdderAndSubtractor.vhd',
  'OperatorSelector.vhd',
  'Multiplier.vhd',
  'Divider.vhd',
  'test.vhd',
]