# File names are either absolute or relative to the parent folder of the
# vhdl_ls.toml file and supports glob-style patterns.

[libraries]

lib1.files = [
  'CalculatorVHDL.vhd',
  'FSM.vhd',
  'FullAdder.vhd',
  'BinaryAdderAndSubtractor.vhd',
  'OperatorSelector.vhd',
  'Multiplier.vhd',
  'Divider.vhd',
  'SignDetector.vhd',
  'SignDetectorPreview.vhd',
  'BinaryToBCDConverterADD.vhd',
  'BinaryToBCDConverterSUB.vhd',
  'BinaryToBCDConverterMUL.vhd',
  'BinaryToBCDConverterDIV.vhd',
  'BCDto7Segment.vhd',
  'BinaryToBCDConverterPreviewA.vhd',
  'BinaryToBCDConverterPreviewB.vhd',
  'MUX6to3_Resullt.vhd',
  'MUX6to3_Remainder.vhd'
]